apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innovatech-frontend
  template:
    metadata:
      labels:
        app: innovatech-frontend
    spec:
      containers:
        - name: innovatech-frontend
          image: innovatech-frontend-image:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: innovatech-frontend-svc
spec:
  selector:
    app: innovatech-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer