apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS innovatech_db;
    CREATE USER IF NOT EXISTS 'innovatech_admin'@'%' IDENTIFIED BY 'AdminPass2026!';
    GRANT ALL PRIVILEGES ON innovatech_db.* TO 'innovatech_admin'@'%';

    FLUSH PRIVILEGES;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: innovatech-db-secrets
                  key: mysql-root-password
          volumeMounts:
            - name: mysql-init-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-init-volume
          configMap:
            name: mysql-init-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP