apiVersion: v1
kind: Secret
metadata:
  name: innovatech-db-secrets
type: Opaque
stringData:
  mysql-root-password: "RootPassword2026!"
  db-name: "innovatech_db"
  db-user: "innovatech_admin"
  db-pass: "AdminPass2026!"